excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://clevert-pretto.github.io
title: C-The hobbyis
tagline: A technical/ non-technical discription of my life.
description: My awesome new site
paginate: 5
