excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://imhobbyist.github.io
title: I am Electronics freak
tagline: The things I care about
description: Let's learn, share, discuss and build
paginate: 5
